# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    image: mdillon/postgis
    # environment:
    #   - POSTGRES_USER=${PG_USER:zrc}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:zrc}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: nlxio/gemma-zrc
    environment:
      - DJANGO_SETTINGS_MODULE=zrc.conf.docker
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
