openapi: 3.0.0
info:
  title: Zaakregistratiecomponent (ZRC) API documentatie
  description: TODO
  contact:
    email: support@maykinmedia.nl
  license:
    name: EUPL 1.2
  version: '1'
security:
  - basic: []
paths: {}
servers:
  - url: /
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
