openapi: 3.0.0
info:
  title: Zaakregistratiecomponent (ZRC) API documentatie
  description: TODO
  contact:
    email: support@maykinmedia.nl
  license:
    name: EUPL 1.2
  version: '1'
security:
  - basic: []
paths:
  '/api/v{version}/statussen/':
    get:
      operationId: status_list
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Status'
      tags:
        - api
    post:
      operationId: status_create
      description: ''
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      tags:
        - api
      requestBody:
        $ref: '#/components/requestBodies/Status'
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
  '/api/v{version}/statussen/{id}/':
    get:
      operationId: status_read
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      tags:
        - api
    put:
      operationId: status_update
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      tags:
        - api
      requestBody:
        $ref: '#/components/requestBodies/Status'
    patch:
      operationId: status_partial_update
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      tags:
        - api
      requestBody:
        $ref: '#/components/requestBodies/Status'
    delete:
      operationId: status_delete
      description: ''
      responses:
        '204':
          description: ''
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this status.
        required: true
        schema:
          type: integer
      - name: version
        in: path
        required: true
        schema:
          type: string
  '/api/v{version}/zaken/':
    get:
      operationId: zaak_list
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zaak'
      tags:
        - api
    post:
      operationId: zaak_create
      description: ''
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zaak'
      tags:
        - api
      requestBody:
        $ref: '#/components/requestBodies/Zaak'
    parameters:
      - name: version
        in: path
        required: true
        schema:
          type: string
  '/api/v{version}/zaken/{id}/':
    get:
      operationId: zaak_read
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zaak'
      tags:
        - api
    put:
      operationId: zaak_update
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zaak'
      tags:
        - api
      requestBody:
        $ref: '#/components/requestBodies/Zaak'
    patch:
      operationId: zaak_partial_update
      description: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Zaak'
      tags:
        - api
      requestBody:
        $ref: '#/components/requestBodies/Zaak'
    delete:
      operationId: zaak_delete
      description: ''
      responses:
        '204':
          description: ''
      tags:
        - api
    parameters:
      - name: id
        in: path
        description: A unique integer value identifying this zaak.
        required: true
        schema:
          type: integer
      - name: version
        in: path
        required: true
        schema:
          type: string
servers:
  - url: /
components:
  requestBodies:
    Status:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status'
      required: true
    Zaak:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Zaak'
      required: true
  securitySchemes:
    basic:
      type: http
      scheme: basic
  schemas:
    Status:
      required:
        - zaak
        - status_type
        - datum_status_gezet
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaak:
          title: Zaak
          type: string
          format: uri
        status_type:
          title: Status type
          type: string
          format: uri
          maxLength: 200
          minLength: 1
        datum_status_gezet:
          title: Datum status gezet
          description: De datum waarop de ZAAK de status heeft verkregen.
          type: string
          format: date-time
        statustoelichting:
          title: Statustoelichting
          description: >-
            Een, voor de initiator van de zaak relevante, toelichting op de
            status van een zaak.
          type: string
    Zaak:
      required:
        - zaakidentificatie
      type: object
      properties:
        url:
          title: Url
          type: string
          format: uri
          readOnly: true
        zaakidentificatie:
          title: Zaakidentificatie
          description: >-
            De unieke identificatie van de ZAAK binnen de organisatie die
            verantwoordelijk is voor de behandeling van de ZAAK.
          type: string
          maxLength: 40
          minLength: 1
        status:
          title: Status
          type: string
          format: uri
          readOnly: true
